# -*- mode: ruby -*-
# vi: set ft=ruby :VAGRANTFILE_API_VERSION = "2"

Vagrant.configure("2") do |config|
config.ssh.insert_key = false
config.vm.provider :virtualbox do |vb|
vb.customize ["modifyvm", :id, "--memory", "256"] end

# sysdig on centos .
config.vm.define "app1" do |app|
app.vm.hostname = "app1.dev"
app.vm.box = "centos/7"
app.vm.network "private_network", ip: "192.168.44.10"
end

# Application server 3.
config.vm.define "app2" do |app|
app.vm.hostname = "app2.dev"
app.vm.box = "ubuntu/trusty64"
app.vm.network "private_network", ip: "192.168.44.20"
end


end